//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chatbotrepo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestsTbl
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> monitor_id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual CustomersTbl CustomersTbl { get; set; }
        public virtual MonitorsTbl MonitorsTbl { get; set; }
    }
}
